### ISSUE TITLE
AttributeError: module 'ansible.constants' has no attribute 'ANSIBLE_SSH_CONTROL_PATH'

### ISSUE THREAD

**Issue by dmp1ce** [andreasscherbaum/ansible-lxc-ssh#30]
I started getting this error today after upgrading Ansible, I think. `AttributeError: module 'ansible.constants' has no attribute 'ANSIBLE_SSH_CONTROL_PATH'`

Ansible environment on Arch Linux:
```
$ ansible --version
ansible [core 2.11.0] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/david/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/david/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.4 (default, Apr 20 2021, 15:51:38) [GCC 10.2.0]
  jinja version = 2.11.3
  libyaml = True
```

My error:
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ansible/executor/task_executor.py", line 159, in run
    res = self._execute()
  File "/usr/lib/python3.9/site-packages/ansible/executor/task_executor.py", line 533, in _execute
    self._connection = self._get_connection(cvars, templar)
  File "/usr/lib/python3.9/site-packages/ansible/executor/task_executor.py", line 866, in _get_connection
    connection, plugin_load_context = self._shared_loader_obj.connection_loader.get_with_context(
  File "/usr/lib/python3.9/site-packages/ansible/plugins/loader.py", line 837, in get_with_context
    obj.__init__(instance, *args, **kwargs)
  File "/home/david/Workspace/my_project/connection_plugins/lxc_ssh.py", line 131, in __init__
    self.control_path = C.ANSIBLE_SSH_CONTROL_PATH
AttributeError: module 'ansible.constants' has no attribute 'ANSIBLE_SSH_CONTROL_PATH'
fatal: [omd2]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

```

**Comment by dmp1ce** [comment]
Asking for help on IRC. I think the module needs to be updated to delcare plugin parameters. https://docs.ansible.com/ansible/latest/dev_guide/developing_plugins.html#plugin-configuration-documentation-standards

```
10:43 <dave_uy> I recently updated to 2.11.0 on Arch Linux and a module I was using isn't working anymore. I created an issue here: https://github.com/andreasscherbaum/ansible-lxc-ssh/issues/30
10:43 <dave_uy> Any ideas on what could have changed? Arch Linux added an "ansible-core" package recently as well.
10:45 <@bcoca> that setting was moved to the ssh plugin, so its no longer a global, connection plugin must be modified to use proper plugin config
10:47 <dave_uy> Is this a recent change in 2.11.0?
10:48 <@bcoca> not really, that setting was obsollete for a long time, think it was completely removed in 2.10
10:50 <tadeboro> It is a bit confusing since it is still documented at https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-ssh-control-path without any comment about being just a proxy for some ssh parameter.
10:53 <tadeboro> Hmm, it looks like it is gone from 2.11, not 2.10. https://docs.ansible.com/ansible-core/2.11/reference_appendices/config.html does not contain that option anymore.
10:54 <@bcoca> there is pr for 2.10 removal, but not merged yet
10:54 <tadeboro> Aaa, that would explain the docs, yes.
10:56 <@bcoca> the config should still work since plugins used backwards compatible entries
10:57 <@bcoca> its the code using the constants directly that is broken
10:59 <dave_uy> So, what should I be importing instead of "from ansible import constants as C"
11:05 <tadeboro> dave_uy: Thsi should be a connectin plugin parameter. https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/ssh.py#L236 is how ssh plugin declares it.
11:07 <tadeboro> dave_uy: It looks like the lxc_ssh plugin have some catching up to do.
11:08 <dave_uy> OK. I don't remember what it means for the plugin to have a connection plugin parameter but I'll add that information to the issue.
11:09 <@bcoca> dave_uy: it means it has to decleare them in the DOCUMENTATION section, which then will auto create the option and populate it from core, then you just have to get_option('name')
11:09 <@bcoca> it is in plugin dev docs
11:09 <tadeboro> dave_uy: ssh_lxc is a connection plugin with no parameters roght now (it fetches information it needs from different sources). The Right Way (TM) is to declare plugin parameters that users can then use to control the behavior.
11:09 <tadeboro> *right
11:11 <dave_uy> Thank you!
```

**Comment by andreasscherbaum** [comment]
@dmp1ce I've followed the IRC log, but I was not able to figure out which version made this obsolete.
Which in turn raises another question: which Ansible version supports this, and which does not.
Were you able to figure that out?

**Comment by dmp1ce** [comment]
This issue effects versions `>= 2.11.0`.

**Comment by andreasscherbaum** [comment]
OK, please let me clarify: the proposed PR, which versions does it support? What is the minimum Ansible version required for the PR?

It obviously works with 2.11, but I don't want to break earlier versions which are still supported.

(and I should find a way to have the regression tests work with multiple Ansible versions)

**Comment by dmp1ce** [comment]
I don't know how far back the PR will work for, but I'm guessing pretty far back. The new way of declaring variables has been there for awhile I think.

Why not keep `master` on the latest version and support older versions with branches?

**Comment by andreasscherbaum** [comment]
Dunno, so far I was able to avoid doing releases, because the plugin is easy enough and works with a wide range of supported versions.

**Comment by dmp1ce** [comment]
The `2.11.0` update might be a little harder to support old versions, depending on how far back you want to support on `master`.

**Comment by andreasscherbaum** [comment]
Well, not good:

```
Cannot add PPA: 'ppa:~ansible/ubuntu/ansible-2.11'.
The team named '~ansible' has no PPA named 'ubuntu/ansible-2.11'
Please choose from the following available PPAs:
 * 'ansible':  ansible
 * 'ansible-1.9':  ansible-1.9
 * 'ansible-2.1':  ansible-2.1
 * 'ansible-2.10':  Ansible and ansible-base 2.10
 * 'ansible-2.2':  ansible-2.2
 * 'ansible-2.3':  ansible-2.3
 * 'ansible-2.4':  ansible-2.4
 * 'ansible-2.5':  ansible-2.5
 * 'ansible-2.6':  ansible-2.6
 * 'ansible-2.7':  Ansible-2.7
 * 'ansible-2.8':  Ansible 2.8
 * 'ansible-2.9':  Ansible 2.9
 * 'bubblewrap':  bubblewrap
 * 'proot':  proot
 * 'testing-ansible':  testing-ansible
 * 'testing-ansible-2.10':  testing-ansible-2.10
 * 'testing-ansible-2.8':  testing-ansible-2.8
 * 'testing-ansible-2.9':  testing-ansible-2.9
 * 'testing-ansible-3':  testing-ansible-3
 * 'testing-ansible-4':  testing-ansible-4
 ```

No 2.11 available here: https://launchpad.net/~ansible/+archive/ubuntu/ansible
Need to find another way to test multiple versions.

**Comment by andreasscherbaum** [comment]
Ok, found a way to test different Ansible versions.
